name: Label and assign PR
on:
  pull_request:
    types:
      - reopened
      - opened
jobs:
  label_and_assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ["CervinoB"]
            })
            github.rest.pulls.createReviewRequest({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              reviewers: ["CervinoB"]
            })
            github.rest.pulls.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["triage"]
            })
